---
author: Tomas Ruiz
title: Research Assistant
format:
  classic-cv-pdf: default
cvfooter:
  left: "tomasruizt.github.io"
  right: "tomas.ruiz.te@gmail.de"
cvcolor: 58748F #without `#`
cvfont: raleway #texlive fonts like raleway,fetamont,gillius,comfortaa
cvmeta:
  - title: Status
    left: Research Assistant at LMU Munich
    right: Munich, Germany
  - title: Field
    left: Machine Learning, Multi-modal AI
    right: +49 176 817 933 17
  - title: Techs
    left: Python, R, C#, Java, AWS, Django, FastAPI, PostgreSQL, Hadoop, Spark
    right: tomas.ruiz.te@gmail.de
execute:
  echo: false
---

```{r}
#| label: cvevents
cvevents <- function(tbl, when, what, where, details) {

    command_start <- "\\cvevent"

    res <- paste0(
        command_start, "{", tbl[[when]], "}", 
        "{", tbl[[what]], "}",
        "{", tbl[[where]], "}")
    
    tbl[[details]] <- sapply(tbl[[details]], function(x) paste0("{", x, "}", collapse = ","))
    res <- paste0(res, "{",tbl[[details]],"}")

    cat(res, sep = "\n")
}
```

# Summary

Research assistant at the LMU Munich at the intersection of Machine Learning and Social Media, particularly on multi-modal ML. In previous jobs, I worked as a software engineer in different companies and start-ups.

# Experience


```{r}
#| label: experience
#| output: asis
tibble::tribble(
    ~role, ~institution, ~dates, ~details,
    "Senior Software Engineer", "Allianz Global Investors - Munich, Germany", "03/2023 - 05/2024",
    "[Python, C#]: I wrote C# core libraries to simulate the performance of trading strategies for options & derivatives, as well as Python packages to orchestrate scenario simulations, interact with diverse data systems over REST, with SQL Databases, etc. I collaborated closely with quantitative researchers and financial engineers to ship our product. I learned about financial mathematics, portfolio management & risk modeling.",
    "Software Engineer", "Preisenergie GmbH - Munich, Germany", "03/2021 - 02/2023", "[Python, R, REST, PostgreSQL, Django, FastAPI, DDD, TDD]: Designed and built RESTful applications with Django and FastAPI to calculate contract prices for existing utility customers. Rearchitected and refactored a large untested legacy codebase towards a Domain-Driven-Design based on R packages with a clear separation of concerns. Designed, implemented and tested a price optimization algorithm using Quadratic Programming with ~10âµ variables. Improved expected CLV over the existing algorithm by 20\\% on average. Extended a web application to manage and analyze data on energy contracts. Translated the product roadmap into a system design, onboarded new developers, performed 1on1s, code reviews & retrospective meetings.",
    "Software Engineering Intern - Core Machine Learning", "Amazon - Berlin, Germany", "09/2017 - 02/2018", "[Java, AWS]: Wrote a tool to benchmark cutting-edge Multiarmed-Bandits models for product recommendation. I released it on AWS, so that all internal development teams in Amazon and AWS could asses the potential revenue increases based on their own datasets.",
    "Bachelor's Thesis", "BMW Group - Munich, Germany", "03/2017 - 08/2017", "[Python, Spark, Hadoop, Tableau]: Evaluated the query latency, throughput, and DB consistency of an application that monitored the engine manufacturing process."
) |>
    cvevents(when = "dates", what = "role", where = "institution", details = "details")
```

# Education

```{r }
#| label: education
#| output: asis
tibble::tribble(
    ~role, ~institution, ~dates, ~details,
    "Research Assistant", "Ludwig Maximilian University of Munich", "06/2024 - Present", "Researching on the intersection of machine learning and computational social science. In my project, I apply large multi-modal models (VLM) to understand and classify content from social media (videos, images, audio, & text).",
    "Master of Science - Computer Science", "Technical University of Munich", "04/2018 - 02/2021", "My thesis was on the topic of Reinforcement Learning applied to robotics, and learning useful skills with weak supervision. I took courses such as Machine Learning, Deep Learning, Convex Optimization, and more.",
    "Bachelor of Science - Engineering Science", "Technical University of Munich", "09/2013 - 08/2017", "My thesis was with BMW Group, where I worked with a Hadoop cluster and evaluated its query throughput and latency on challenging database queries. I took courses in computer science such as Algorithms and Data Structures, Databases, etc. And also classic engineering courses such as Partial Differential Equations, Thermodynamics, etc."
) |>
    cvevents(when = "dates", what = "role", where = "institution", details = "details")
```
