run:
	quarto preview cv.qmd


# The extension (_extensions/schochastics/modern2-cv) is checked into git
# with custom modifications (spacing, icon sizes, etc.).
# Do NOT run "quarto use template schochastics/modern2-cv" as it would
# overwrite these customizations.