run:
	quarto preview cv.qmd


# Comment (2026-02-02)
# I'm not sure if the installation instruction below are correct.
# They seem to assume that the extension is not checked into git.
# However, I have modified the extension code to ues a narrower sidebar,
# and this would not work anymore if the extension is not checked into git.
install:
	echo "Please select: trust authors [yes]"
	echo "create subdirectory [no]"
	echo "install extensions [yes]"
	echo "overwrite cv.qmd [no]"
	quarto use template schochastics/modern2-cv