run:
	quarto preview cv.qmd

install:
	echo "Please select: trust authors [yes]"
	echo "create subdirectory [no]"
	echo "install extensions [yes]"
	echo "overwrite cv.qmd [no]"
	quarto use template schochastics/modern2-cv