project:
  type: website
  output-dir: docs

website:
  title: "Tomas' Site"
  site-url: "https://tomasruizt.github.io/"
  description: "Tomas Ruiz's blog"
  navbar:
    right:
      - subscribe.qmd
      - about.qmd
      - icon: rss
        href: index.xml
      - icon: linkedin
        href: https://www.linkedin.com/in/tomas-ruiz-649907b3/
      - icon: github
        href: https://github.com/tomasruizt
format:
  html:
    theme: cosmo
    css: styles.css



