project:
  type: website
  output-dir: docs

website:
  title: "Tomas' Site"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/tomas-ruiz-649907b3/
      - icon: github
        href: https://github.com/tomasruizt
format:
  html:
    theme: cosmo
    css: styles.css



